# Generated by Django 3.2.6 on 2024-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='llm_nudges',
            field=models.CharField(default='ayoub', max_length=2000),
            preserve_default=False,
        ),
    ]
