# Generated by Django 3.2.6 on 2024-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0002_recommendations_llm_nudges'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedrecipe',
            name='llm_hashtag',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
