# Generated by Django 3.2.6 on 2024-11-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='sus_1',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='sus_1'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='sus_2',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='sus_2'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='sus_3',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='sus_3'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='sus_4',
            field=models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=300, verbose_name='sus_4'),
        ),
    ]
