# Generated by Django 3.2.6 on 2024-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0002_auto_20241121_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='llm_nudges',
            field=models.CharField(default='test', max_length=2300),
            preserve_default=False,
        ),
    ]
