# Generated by Django 3.2.6 on 2024-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0003_recommendations_llm_nudges'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedrecipe',
            name='llm_explanation',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='EatingGoals',
            field=models.CharField(choices=[(None, ''), ('Lose Weight', 'Lose Weight'), ('Gain Weight', 'Gain Weight'), ('No Goal', 'No Goal')], default=None, max_length=300, verbose_name='HomeCook'),
        ),
    ]
