# Generated by Django 3.2.6 on 2022-12-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='CookingExp',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='CookingTime',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Depression',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='EatingGoals',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='HomeCook',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='PhysicalActivity',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='RecipeWebUsage',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='SleepHours',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Weight',
        ),
    ]
