# Generated by Django 3.2.6 on 2022-12-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0002_auto_20221204_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session_id',
        ),
    ]
