# Generated by Django 3.2.6 on 2024-11-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels_Nudges', '0002_auto_20241125_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='effectiveness',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='persuasiveness',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='evaluatechoices',
            name='understandability',
        ),
    ]
